name: pre-commit

on:
  pull_request:
  push:
    branches:
      - master
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    env:
      TERRAFORM_DOCS_VERSION: v0.16.0
      TFLINT_VERSION: v0.33.0
      CHECKOV_VERSION: 2.0.258
      TFSEC_VERSION: v0.58.14

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2

      - name: Install terraform-docs
        run: |
          curl -Lo ./terraform-docs.tar.gz https://github.com/terraform-docs/terraform-docs/releases/download/$TERRAFORM_DOCS_VERSION/terraform-docs-$TERRAFORM_DOCS_VERSION-$(uname)-amd64.tar.gz
          tar -xzf terraform-docs.tar.gz
          chmod +x terraform-docs
          sudo mv terraform-docs /usr/local/terraform-docs

      - name: Install tflint
        run: "curl -s https://raw.githubusercontent.com/terraform-linters/tflint/$TFLINT_VERSION/install_linux.sh | bash"

      - name: Install checkov
        run: "pip install checkov==$CHECKOV_VERSION"

      - name: Install tfsec
        run: |
          sudo snap install --classic go
          go install github.com/aquasecurity/tfsec/cmd/tfsec@$TFSEC_VERSION

      - name: Run pre-commit
        uses: pre-commit/action@v2.0.3

  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
          
