repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.55.0
    hooks:
      - id: terraform_tflint
        args:
          - --args=--enable-rule=terraform_documented_variables
      - id: terraform_fmt
      - id: checkov
      - id: terraform_docs
        args:
          - --hook-config=--path-to-file=./terraform-{{cookiecutter.provider}}-{{cookiecutter.module_name}}/README.md        # Valid UNIX path. I.e. ../TFDOC.md or docs/README.md etc.
          - --hook-config=--add-to-exiting-file=true      # Boolean. true or false
          - --hook-config=--create-file-if-not-exist=true # Boolean. true or false
