name: Lint
on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  tflint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout source code

      - uses: actions/cache@v2
        name: Cache plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

      - uses: terraform-linters/setup-tflint@v1
        name: Setup TFLint
        with:
          tflint_version: v0.29.0

      - name: Show version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init --module ./terraform-\{\{cookiecutter.provider\}\}-\{\{cookiecutter.module_name\}\}

      - name: Run TFLint
        run: tflint -f compact --module ./terraform-\{\{cookiecutter.provider\}\}-\{\{cookiecutter.module_name\}\} 

  terraform:
    needs: tflint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout source code
      
      - uses: hashicorp/setup-terraform@v1
        name: Setup Terraform
        with:
          terraform_version: 1.0.0
