name: Check Terraform Module
on:
  pull_request:
  push:
    branches:
      - master
      - main
      
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkoutv2

      #- name: Setup TFLint
      #  uses: terraform-linters/setup-tflint@v1
      #  with:
      #    tflint_version: v0.29.0
#
      #- name: Init TFLint
      #  run: tflint --init
#
      #- name: Run TFLint
      #  run: tflint -f compact
